### ISSUE TITLE
Meetable events should have a Code of Conduct field for one or more URLs

### ISSUE THREAD

**Issue by tantek** [aaronpk/Meetable#84]
Typical communty events require agreeing to a Code of Conduct in order to RSVP and participate. Meetable should have a field to enter one or more Code of Conduct URLs, and then show them prominently on the event, preferably right before / next to any user interface to RSVP.

Use-case for a Code of Conduct field: IndieWeb events always require agreeing to the [IndieWeb Code of Conduct](https://indieweb.org/code-of-conduct).

Use-case for a field for multiple Code of Conduct URLs: IndieWeb events hosted at a Mozilla office require agreeing to both the IndieWeb Code of Conduct and the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).

The Code of Conduct link(s) should be prominently publicly displayed on Meetable event pages, preferably adjacent to / before any RSVP user interface or display.

(Originally published at: https://tantek.com/2020/062/b2/)

**Comment by aaronpk** [comment]
Events now have a field to add one or more code of conduct URLs.

Example: https://events.indieweb.org/2020/06/indieweb-summit-2020-kJqF29QR3U49

I chose to display this under the website/ticket URL rather than next to the RSVP button since the RSVP section isn't always visible on Meetable installs, plus I couldn't figure out a good design for placing it under there either.
